name: Creat Action Workflow

on: 
  [create,push]

jobs:
  release-git-action:
    if: github.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Branch name
        run: 
          echo $GITHUB_REF_TYPE
