name: Create File Workflow

on:
  push:
    

jobs:
  create-file-job:
    runs-on: ubuntu-latest
    steps:
      - name: Push random files
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHUB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "bot@bot.com"
          git config --global user.name "bot"
          git config --global init.defaultBranch main
          git branch -m master main
          git pull origin main
          git fetch -a
          # git branch
          
          git checkout 'main'
          echo $RANDOM >> random.txt
          git add .
          git commit -m "random file"
          git branch --set-upstream-to=origin/main
          git push