name: Cron Workflow

on:
  pull_request:
    types:
      - "closed"
  # schedule:
  #   - cron: "0/5 * * * *" # "m h DoM M DoW"

jobs:
  run-cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          echo $GITHUB_REPOSITORY