name: Decrypt file Workflow

env:
  PASSPHRASE: ${{secrets.PASSPHRASE}}

on:
 push:

jobs:
  run-file-decryption:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3.3.0 
      - name: Decrypt file
        run: |
          echo $PASSPHRASE
          gpg  --batch --yes --decrypt
           --passphrase="$PASSPHRASE" --output $HOME/secrets.json mysecret.json.gpg
      - name: Print file
        run: cat $HOME/secrets.json
