name: Matrix 

on: push

jobs:
  node_version:
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node_version: [14, 16, 18]
        include: 
          - os: ubuntu-latest
            node_version: 14
            is_node_14: "true"
        exclude:
          - os: windows-latest
            node_version: 16
    runs-on: ${{ matrix.is_node_14}}
    env:
      IS_NODE_14: ${{ matrix. }}
    steps:
      - name: Check Version
        run: node -v
      - name: Update Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check Upgraded Version
        run: node -v
      - name: Log node version
        run: |
          echo $IS_NODE_14