name: Matrix 

on: push

jobs:
  node_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Version
        run: node -v
      - name: Update Version
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check Upgraded Version
        run: node -v