name: Matrix 

on: push

jobs:
  node_version:
    strategy:
      fail-fast: true
      matrix: 
        os: [ubuntu-latest, windows-latest]
        node_version: [14, 16, 18]
      
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check Version
        run: node -v
      - name: Update Version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Check Upgraded Version
        run: node -v